### ISSUE TITLE
The sphere particles collision issue

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#1]
After a minute of running the GUI rain form a larger particles
<img width="1680" alt="screen shot 2015-11-09 at 12 46 29 pm" src="https://cloud.githubusercontent.com/assets/14968599/11046076/0eae1d3c-86e0-11e5-8e92-d47657979654.png">

The Git hash is: 150a420bb1709cbb9342ab42d365968aa507bfae

**Comment by maxhkohl** [comment]
Drops are no longer allowed to combine, I fixed this by setting the Drop prefab's maximum mass (Script parameter) equal to the Drop's RigidBody mass and gameObject scale.

This was fixed in commit: 07b5f57 and is visible on the most recent commit, ec4d318

**Comment by Kadi0** [comment]
Tnx Max
Can I test the current version
