### ISSUE TITLE
Still can't be launched

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#12]
Hey Max,
Thanks for adding the builds. Unfortunately, I still can't open it from just clicking on the icon.
I know how to build it, but this is just for Faulk

<img width="1271" alt="e" src="https://cloud.githubusercontent.com/assets/14968599/11461061/060ce36c-96b1-11e5-87c1-eebe8a1a11be.png">

**Comment by maxhkohl** [comment]
Can you run a build on the most recent commit and push your binary after confirming that it works on your machine? We will need to have you build in parallel with me from now on :[

**Comment by Kadi0** [comment]
That is fine
When can I do that so that we don't have to merge ?

**Comment by Kadi0** [comment]
Max
I pushed the Mac build today.

Please ping me each time that you make a push so that I do the rebuild

I'll leave this open for us to go back and forth 

Thanks

**Comment by Kadi0** [comment]
This is funny
I can run your build
