### ISSUE TITLE
Toggle On/Off Stopped running

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#2]
I was testing the river model and before the vector runs out of drops I stopped the rain. Then tried to switch it back On but it did not start the rain again. So, as you can see, this is not the max n of spheres 
<img width="1680" alt="screen shot 2015-11-15 at 3 53 56 pm" src="https://cloud.githubusercontent.com/assets/14968599/11171937/ad7f51bc-8bb1-11e5-9e65-54225a583b25.png">

**Comment by maxhkohl** [comment]
Fixed via commit hash # 8cf5b0e 

I had not set up the GUI connections to the RiverGrid controls - thanks for spotting this!
