### ISSUE TITLE
Rain controller does not work

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#3]
I think that this controller stopped changing the rate of the spheres dropped. Pic is not helpful but one thing to note is FPS
<img width="1680" alt="screen shot 2015-11-15 at 3 43 14 pm" src="https://cloud.githubusercontent.com/assets/14968599/11171992/7089f216-8bb2-11e5-9f7d-4be43d269982.png">

**Comment by maxhkohl** [comment]
Fixed via commit hash # 8cf5b0e 

I had not set up the RiverGridController script appropriately in the RiverGrid prefab - I forgot to include a maximum time between drops! Good catch, Majeed!

**Comment by Kadi0** [comment]
Thank Max
