### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#4]
<img width="1680" alt="screen shot 2015-11-20 at 11 52 55 am" src="https://cloud.githubusercontent.com/assets/14968599/11310290/a25c3db6-8f7d-11e5-8ad8-97a6254f1c6e.png">
<img width="1680" alt="screen shot 2015-11-20 at 11 54 08 am" src="https://cloud.githubusercontent.com/assets/14968599/11310291/a3e9afe2-8f7d-11e5-9fa4-a58136691e25.png">

**Comment by maxhkohl** [comment]
Majeed, I imported a standard asset package from Unity to deal with our new Camera model. Please do the following and tell me if it fixes the bug:
1. Click on "Assets" in the top bar next to File, Edit, and GameObject
2. Click "Import Package" -> "Characters"

That should fix the problem - it is an editor specific issue, and I thought that updating the project settings would fix it - apparently I am wrong :[

**Comment by Kadi0** [comment]
That fixed it
Thanks Max

**Comment by Kadi0** [comment]
fixed
