### ISSUE TITLE
No rain

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#5]
I just pulled and it does not seem to still drop the rain
<img width="1680" alt="screen shot 2015-11-23 at 11 34 37 am" src="https://cloud.githubusercontent.com/assets/14968599/11347482/84a27db6-91d6-11e5-96f9-6701d285c94d.png">

**Comment by maxhkohl** [comment]
This should be fixed via this commit: https://github.com/TeamIndex3/WatershedSimulator/commit/eb360ae05750bc8179275990f4333cc8fe3f2bf1
Can you confirm on your machine?
