### ISSUE TITLE
Other view

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#6]
When I switch to the other view, my track pad can't navigate to the other side of the mountain
<img width="1680" alt="screen shot 2015-11-23 at 11 36 04 am" src="https://cloud.githubusercontent.com/assets/14968599/11347573/fbe07bbc-91d6-11e5-8b4f-788e2293694d.png">

**Comment by maxhkohl** [comment]
Majeed, 

Try using the W key to move forward, the S key to move backwards, and the space key to jump. 
Let me know if that works!

-Max

**Comment by Kadi0** [comment]
It is actually fun to navigate with them
That worked
Thanks
