### ISSUE TITLE
Rain fall not working

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#7]
<img width="1680" alt="screen shot 2015-11-23 at 11 43 55 am" src="https://cloud.githubusercontent.com/assets/14968599/11347696/8cd7baf4-91d7-11e5-94c8-314d9542881f.png">

**Comment by maxhkohl** [comment]
This should be fixed via: https://github.com/TeamIndex3/WatershedSimulator/commit/006a66437840b231641342ae2f2ee2b55c787379
