### ISSUE TITLE
FPS < 20

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#8]
I switch rain discharge to the highest level, switch to the matrix view and changed the hight 
Then, FPS went below 20 FPS
<img width="1680" alt="screen shot 2015-11-24 at 12 37 55 pm" src="https://cloud.githubusercontent.com/assets/14968599/11380096/e7951780-92a8-11e5-8dc7-d03b104a6656.png">

**Comment by maxhkohl** [comment]
Majeed, you are a mind reader! I just pushed code ( https://github.com/TeamIndex3/WatershedSimulator/commit/26b621965bd5e5eda2acc12bcbe3b5c5b83447a2 ) which attempted to fix the frame rate issue. 

Can you re-pull and test again? My frame rate stays above 30 for at least 7 minutes with the new settings.

**Comment by Kadi0** [comment]
On it

**Comment by Kadi0** [comment]
This is great Max 
Thanks 
That fixed it

**Comment by maxhkohl** [comment]
Thanks Majeed! 

Any chance you could leave the program running for at least 10-30 minutes and see if the frame rate ever gets below 20?

**Comment by Kadi0** [comment]
Sure

**Comment by Kadi0** [comment]
I ran it for a while
No issues with FPS
