### ISSUE TITLE
Toggle can't reRain

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#9]
<img width="1680" alt="screen shot 2015-11-24 at 8 52 25 pm" src="https://cloud.githubusercontent.com/assets/14968599/11388650/60037236-92ed-11e5-9b73-63d6ec4cc793.png">

**Comment by maxhkohl** [comment]
Fixed via commit hash: https://github.com/TeamIndex3/WatershedSimulator/commit/ebcff3a637a255dc66987fd07c962c9e853837d4
